spring.application.name=demo-project-for-banking-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/bankingDB
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=Anishek@15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
